### ISSUE TITLE
https

### ISSUE THREAD

**Issue by akuckartz** [okfde/ris-web#10]
Der Zugriff sollte per default per https erfolgen oder zumindest ermöglicht werden. Insbesondere die Übertragung von Ortsangaben als auch z.B. Suchen nach bestimmten gesundheitlichen oder politischen Themen müssen verschlüsselt möglich sein.

Dazu gibt es auch neue Grundsatzempfehlungen des Internet Architecture Board (IAB):

IAB Statement on Internet Confidentiality
https://www.iab.org/2014/11/14/iab-statement-on-internet-confidentiality/

Internet Society Commends Internet Architecture Board Recommendation on Encryption-by-Default for the Internet
http://www.internetsociety.org/news/internet-society-commends-internet-architecture-board-recommendation-encryption-default

**Comment by the-infinity** [comment]
Ist eingeplant, dafür müssen wir uns aber zunächst final auf die URL festlegen. :)

**Comment by akuckartz** [comment]
Wenn ich das richtig sehe, dann ist dieses Issue erledigt.
