### ISSUE TITLE
Straßen-Beispielsuchen für Besucher außerhalb der gescrapten Städte

### ISSUE THREAD

**Issue by the-infinity** [okfde/ris-web#18]
Um das Besuchererlebnis für Menschen außerhalb der bereits gescrapten Städte zu verbessern, sollten Beispielstraßen genannt werden, um die Funktionalität von ris-web zu demonstrieren (Vorschlag von Twitter).

**Comment by akuckartz** [comment]
Ohne langes Nachdenken ein paar Vorschläge für Straßen in Köln:
- Eschweilerstraße  (Wohngebiet)
- Portalsgasse (Nähe Rathaus)
- Trankgasse (am Dom)

Eventuell kann auch die Stadtverwaltung um Empfehlungen gebeten werden.

**Comment by the-infinity** [comment]
Überflüssig durch Livesuche in https://github.com/okfde/ris-web/commit/c70b8c9748476c4926ee43d51aa63f8d336039cb
