### ISSUE TITLE
Städte auf der Startseite direkt verlinkbar machen

### ISSUE THREAD

**Issue by the-infinity** [okfde/ris-web#19]
Macht Sinn, wenn man als Stadt auf die Politik Bei Uns oberfläche für die eigene Kommune verlinken will.

**Comment by akuckartz** [comment]
Noch besser wäre eventuell, wenn die Karte mit entsprechendem Ausschnitt als Voreinstellung einfach in einen Internet-Auftritt eingebunden werden kann.

Für den Entwicklungsaufwand sollten die Städte dann aber sinnvollerweise auch eine angemessene Gegenleistung erbringen.

**Comment by akuckartz** [comment]
Anscheinend gibt es gar keine solchen URLs... Das Problem ist aber noch größer: Man kann auch niemandem eine URL schicken, nach deren Abruf ein bestimmter Punkt in der Karte angezeigt wird.

Wie kann das geändert werden?

**Comment by the-infinity** [comment]
Indem man die Kartensuche z.T. verändert. Beim Start von offeneskoeln.de war HTML5 und damit http://spoiledmilk.com/blog/html5-changing-the-browser-url-without-refreshing-page/ noch nicht so verbreitet, so dass man lieber Geschwindigkeit =AJAX statt dauernde Reloads gewählt hat. Sollte man auch bei der Suche einbauen.

**Comment by akuckartz** [comment]
Ok. Zum konkreten Aufbau der URLs mache ich mir Gedanken. U.a. sollten diese möglichst langlebig sein. Ich bin überzeugt, dass es dafür eine ebenso zukunftsträchtige wie einfache Lösung gibt, mit der _alle_ gut leben können.

**Comment by the-infinity** [comment]
Ist fixed in https://github.com/okfde/ris-web/commit/b50877bbcb95efdde7f6f9c1c03068cc8244d4c3
