### ISSUE TITLE
Dokumentation: was tut `generate_xml_sitemaps.py` ?

### ISSUE THREAD

**Issue by akuckartz** [okfde/ris-web#25]
In der Datei `scripts/generate_xml_sitemaps.py` steht am Anfang nur:

> Generiert XML Sitemaps fuer files

Wofür werden die "XML Sitemaps" benötigt?
Für welche Dateien ("files") werden diese generiert?

(Anlass für die Frage ist eine Fehlermeldung die ich bei der Ausführung erhalte.)

**Comment by the-infinity** [comment]
Dort werden sämtliches files und papers (siehe OParl Modell) für Google als Sitemap aufbereitet.

**Comment by akuckartz** [comment]
Danke, dann hängt `ris-web` nicht wirklich davon ab.

Wie auch immer: Ich hatte `generate_xml_sitemaps.py` versehentlich mit dem Argument `5569b1c4a5835f17fd1f6a35` aufgerufen, aber wenn ich im Quelltext nichts übersehen habe, dann wird kein Argument berücksichtigt.

Mit und ohne Parameter bekomme ich aber dieses Verhalten: 

```
(venv)ris@lenny:/srv/www/ris-web$ python scripts/generate_xml_sitemaps.py
[ObjectId('5569b1c4a5835f17fd1f6a35')]
Traceback (most recent call last):
  File "scripts/generate_xml_sitemaps.py", line 163, in <module>
    generate_sitemaps(config)
  File "scripts/generate_xml_sitemaps.py", line 103, in generate_sitemaps
    generate_sitemap(shortlist, sitemap_name)
  File "scripts/generate_xml_sitemaps.py", line 145, in generate_sitemap
    f = open(sitemap_path, 'w')
IOError: [Errno 2] No such file or directory: u'/srv/www/ris-web/webapp/static/sitemap/files_5569b1c4a5835f17fd1f6a35_1.xml'
```

Dazu eine Idee?

**Comment by the-infinity** [comment]
Da fehlt vermutlich der Basisordner sitemap.

**Comment by akuckartz** [comment]
Danke. Nach manuellem Anlegen des Ordners läuft `generate_xml_sitemaps.py` ohne Fehlermeldung durch.

**Comment by akuckartz** [comment]
Kurze Info in Installationsanleitung ergänzt.
