### ISSUE TITLE
Dokumentensuche: "Erstellungsdatum" absteigend sortieren

### ISSUE THREAD

**Issue by akuckartz** [okfde/ris-web#26]
In der Spalte "Erstellungsdatum" werden zuerst die ältesten Zeiträume angezeigt. Besser wäre die Anzeige der jüngsten Zeiträume am Anfang.

**Comment by the-infinity** [comment]
Fixed in https://github.com/okfde/ris-web/commit/c70b8c9748476c4926ee43d51aa63f8d336039cb
