### ISSUE TITLE
Suche nach "Straße und Stadt" fehlerhaft

### ISSUE THREAD

**Issue by TheRadialActive** [okfde/ris-web#30]
[Ich habe es nur auf der politik-bei-uns-Seite (mit Webkit- und Gecko-basierten Browsern) ausprobiert.]

Beim Bestätigen der Suchanfrage unter "Sehen Sie sich an, was die Politik in Ihrer Umgebung macht:" durch Klicken auf die Schaltfläche "Anzeigen" wird nur die Lade-Animation angezeigt, aber keine Inhalte/keine Änderung der Perspektive in der Karte.

**Comment by the-infinity** [comment]
Huch. Der Bug ist neu. Da die Straßensuche aber eh suboptimal war gibt es bei mir lokal bereits eine deutlich schnellere Suche mit Autocomplete. Wird bald eingespielt. Danke für den Hinweis! :)

**Comment by the-infinity** [comment]
Fixed in https://github.com/okfde/ris-web/commit/c70b8c9748476c4926ee43d51aa63f8d336039cb
