### ISSUE TITLE
Suchergebnisse aus anderen Gemeinden ausblenden

### ISSUE THREAD

**Issue by akuckartz** [okfde/ris-web#4]
Bei der Suche nach einer Strasse in einer Stadt werden auch benachbarte Strassen angezeigt. Wenn man dann auf eine Strassenlinie klickt, dann werden bei den Treffern auch andere Gemeinden berücksichtigt, in denen eine gleichnamige Strasse vorkommt. Das dürfte fast nie erwünscht sein.

**Comment by the-infinity** [comment]
Wird mit #8 gelöst.
