### ISSUE TITLE
map error (mapquest)

### ISSUE THREAD

**Issue by eriu** [okfde/ris-web#40]
Die eingebundenen Kartendaten (Mapquest) funktionieren nicht mehr, da Mapquest Dienst deaktiviert hat. 

Alternative leaflet-provider wären z.B.
OSM oder OSM-De

siehe leaflet-extras.github.io/leaflet-providers/

**Comment by the-infinity** [comment]
Sehr gut. Fast in derselben Sekunde habe ich den Fix dazu hochgeladen: https://github.com/okfde/politik-bei-uns-web/commit/3cf86030e7fa1d12b090de3b3d942af06f28a268
Ist gleich auch aktiv.

**Comment by the-infinity** [comment]
Fixed.
