### ISSUE TITLE
System-Objekt hat body url mit ?html=1 am Ende

### ISSUE THREAD

**Issue by gruenzeug** [okfde/ris-web#41]
Das System-Objekt [https://politik-bei-uns.de/oparl](https://politik-bei-uns.de/oparl) enthält:
`"body": "https://politik-bei-uns.de/oparl/body?html=1"`
es sollte jedoch nur
`"body": "https://politik-bei-uns.de/oparl/body"`
sein.

Viele Grüße,
Juka

**Comment by the-infinity** [comment]
Fixed mit https://github.com/okfde/politik-bei-uns-web/commit/319e5ca00735d231e7efd4d1099b312f5f5ce075 
Garstiges Fehlerchen: http://docs.python-guide.org/en/latest/writing/gotchas/
