### ISSUE TITLE
Änderung von "Ausgewählte Region" funktioniert nicht

### ISSUE THREAD

**Issue by akuckartz** [okfde/ris-web#5]
Es danach immer "Deutschland" angezeigt.

**Comment by akuckartz** [comment]
Das "immer" stimmt nicht. Auf einem anderen Gerät passiert das gerade nicht.

**Comment by the-infinity** [comment]
Wo (Browser, Betriebssystem) hat es denn nicht funktioniert? Eigentlich wird die die gewählte Region in der Session abgespeichert.

**Comment by akuckartz** [comment]
Ich bekomme das nicht mehr reproduziert. Vermutlich ein Snafu. Falls es doch wieder auftritt öffne ich ich das Issue wieder.
