### ISSUE TITLE
"Hilfe" verweist auf obsoletes "Open Data Network"

### ISSUE THREAD

**Issue by akuckartz** [okfde/ris-web#9]
Auf der Seite http://opendata-network.org/ steht:

> Diese Netzressource ist archiviert und wird seit Februar 2013 nicht mehr aktualisiert!

**Comment by the-infinity** [comment]
Die Hilfe wird zur Zeit komplett neu geschrieben. Daher sind dort auch noch jede Menge Layoutfehler.

**Comment by akuckartz** [comment]
Der Link ist offenbar bereits entfernt.
